---

- name: "Fetch repo project with type: {{ fetch_type }}"
  ansible.builtin.command: "git {{ fetch_type | default('fetch') }} origin {{ branch }} --tags"
  become: true
  become_user: "{{ app_user }}"
  args:
    chdir: "{{ www_path }}"

- name: Checkout with tag
  when: tag is defined
  ansible.builtin.command: "git checkout tags/{{ tag }}"
  become: true
  become_user: "{{ app_user }}"
  args:
    chdir: "{{ www_path }}"
