---
namespace: hoahovan
name: roles
version: 0.1.2
readme: README.md
authors:
  - Hoa Ho Van <hoahv.vn@gmail.com>
description: Ansible roles list
dependencies:
  community.general: "*"
repository: https://github.com/hoahovan/ansible-roles-list
documentation: https://github.com/hoahovan/ansible-roles-list
homepage: https://github.com/hoahovan/ansible-roles-list
issues: https://github.com/hoahovan/ansible-roles-list/issues
build_ignore: []